adv_config:
    da_net_config:
        act_function: relu
        dropout: 0.0
        layers_width:
        - 768
    da_optimizer_config:
        lr: 0.0001
        weight_decay: 0.001
da_lambda: 0
da_spec_config:
    cmd:
        n_moments: 5
    coral: {}
    dann:
        auto_critic_update: false
        critic_iter: 1
        da_optimizer_config:
            lr: 0.00001
            weight_decay: 0.001
        grad_scale_factor: 1.0
    jdot:
        jdot_alpha: 1.0
    mmd:
        fix_sigma: null
        kernel_mul: 2
        kernel_num: 4
    swd:
        multiplier: 8
        p: 2
    wdgrl:
        critic_iter: 5
        gp_da_lambda: 1.0
da_type: dann
embeds_idx:
- -1
lambda_auto_schedule: True
lambda_final: 0
lambda_inc_steps:   1397
lambda_pretrain_steps:   1397
num_domains: 2
